apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: eu.gcr.io/stromasys-projects/substra-backend
      context: ../../
      docker:
        dockerfile: docker/substra-backend/Dockerfile
      sync:
        manual:
        - src: backend/manage.py
          dest: /usr/src/app/
          strip: backend/
        - src: backend/libs/**/*
          dest: /usr/src/app/libs
          strip: backend/libs/
        - src: backend/substrapp/**/*
          dest: /usr/src/app/substrapp
          strip: backend/substrapp/
        - src: backend/events/**/*
          dest: /usr/src/app/events
          strip: backend/events/
        - src: backend/backend/**/*
          dest: /usr/src/app/backend
          strip: backend/backend/
        - src: backend/node/**/*
          dest: /usr/src/app/node
          strip: backend/node/
        - src: backend/node-register/**/*
          dest: /usr/src/app/node-register
          strip: backend/node-register/
        - src: backend/users/**/*
          dest: /usr/src/app/users
          strip: backend/users/

deploy:
  statusCheckDeadlineSeconds: 600
  helm:
    releases:
      - name: backend-org-1
        chartPath: ../../charts/substra-backend
        namespace: org-1
        valuesFiles: [ values/backend-org-1.yaml ]
        imageStrategy:
          helm: {}
        values:
          backend.image: eu.gcr.io/stromasys-projects/substra-backend
          celerybeat.image: eu.gcr.io/stromasys-projects/substra-backend
          celeryworker.image: eu.gcr.io/stromasys-projects/substra-backend

      - name: backend-org-2
        chartPath: ../../charts/substra-backend
        namespace: org-2
        valuesFiles: [ values/backend-org-2.yaml ]
        imageStrategy:
          helm: {}
        values:
          backend.image: eu.gcr.io/stromasys-projects/substra-backend
          celerybeat.image: eu.gcr.io/stromasys-projects/substra-backend
          celeryworker.image: eu.gcr.io/stromasys-projects/substra-backend

      - name: backend-org-3
        chartPath: ../../charts/substra-backend
        namespace: org-3
        valuesFiles: [ values/backend-org-3.yaml ]
        imageStrategy:
          helm: {}
        values:
          backend.image: eu.gcr.io/stromasys-projects/substra-backend
          celerybeat.image: eu.gcr.io/stromasys-projects/substra-backend
          celeryworker.image: eu.gcr.io/stromasys-projects/substra-backend

      - name: backend-org-4
        chartPath: ../../charts/substra-backend
        namespace: org-4
        valuesFiles: [ values/backend-org-4.yaml ]
        imageStrategy:
          helm: {}
        values:
          backend.image: eu.gcr.io/stromasys-projects/substra-backend
          celerybeat.image: eu.gcr.io/stromasys-projects/substra-backend
          celeryworker.image: eu.gcr.io/stromasys-projects/substra-backend

    flags:
      install: ["--create-namespace"]

profiles:
  - name: prod
    patches:
      - op: replace
        path: /deploy/helm/releases/0/overrides/backend/settings
        value: prod
      - op: replace
        path: /deploy/helm/releases/1/overrides/backend/settings
        value: prod
